const DESCRIPTION_MIN_LENGTH = 10;
const DESCRIPTION_MAX_LENGTH = 200;
const VALID_USER = 1;
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  SERVER_ERROR: 500
};

module.exports={
  DESCRIPTION_MIN_LENGTH,
  DESCRIPTION_MAX_LENGTH,
  HTTP_STATUS,
  VALID_USER
}
